version: '3.8'

services:
  backend:
    build:
      context: ./backend-pos
      dockerfile: dockerfile
    container_name: pos_backend
    env_file:
      - ./backend-pos/.env
    ports:
      - "6001:6001"
    volumes:
      - ./backend-pos:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres-db

  frontend:
    build:
      context: ./frontend-pos
      dockerfile: dockerfile
    container_name: pos_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend-pos:/app
      - /app/node_modules

  postgres-db:
    image: postgres:15-alpine
    container_name: pos-system_db
    restart: always
    
    env_file:
      - ./backend-pos/.env
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pos-system111
      POSTGRES_DB: pos-system
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: